using System;
using System.Data;
using System.Windows.Forms;
using System.Configuration;
using MySql.Data.MySqlClient;
using Pinnacle.Models;

namespace Pinnacle.Tables
{
 public partial class butdroptable : Form
 {
        public butdroptable()
        {
            InitializeComponent();

        }


        // private static string s = ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString;


        private void Butcreate_Click(object sender, EventArgs e)
        {
            try
            {
                DialogResult result1 = MessageBox.Show("Do You want to Create Table in '"+ Class.Users.ProjectID + "'  Database??\n'    ", "'"+ Class.Users.ProjectID + "' - MYSQL - DATABASE", MessageBoxButtons.OKCancel, MessageBoxIcon.Information);
                if (result1.Equals(DialogResult.OK))
                {
                    //"use " + Class.Users.ProjectID + ";"
                    Cursor = Cursors.WaitCursor;
                    string tab =""+
                    "create table IF NOT EXISTS `gtcountrymast` (  `gtcountrymastid` bigint NOT NULL AUTO_INCREMENT,  `countryname` varchar(50) DEFAULT NULL,  `active` char(1) NOT NULL DEFAULT 'T',  `compcode` int DEFAULT NULL,  `username` int DEFAULT NULL,  `createdby` varchar(100) DEFAULT NULL,  `createdon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `modifiedby` varchar(100) DEFAULT NULL,  `ipaddress` varchar(100) DEFAULT NULL,  PRIMARY KEY (`gtcountrymastid`));" +
                    "INSERT INTO gtcountrymast(countryname,active)values('INDIA','T');" +
                    "create table IF NOT EXISTS gtstatemast(gtstatemastid bigint not null auto_increment,   statename  varchar(30), country  bigint,    active   CHAR(1) NOT NULL DEFAULT 'T',   compcode integer, username    integer,    createdby varchar(100),createdon DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,   modifiedby  varchar(100),  ipaddress  varchar(100),primary key (gtstatemastid),foreign key (country) references gtcountrymast(gtcountrymastid));" +
                    "INSERT INTO gtstatemast(statename,country,active)values('TAMILNADU','1','T');" +
                    "create table IF NOT EXISTS gtcitymast(gtcitymastid bigint not null  auto_increment,cityname varchar(50), state bigint,  country bigint,  active CHAR(1) NOT NULL DEFAULT 'T', compcode integer, username integer, createdby varchar(100), createdon DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, modifiedby  varchar(100),  ipaddress  varchar(100), primary key (gtcitymastid),foreign key (country) references gtcountrymast(gtcountrymastid),foreign key (state) references gtstatemast(gtstatemastid));" +
                    "INSERT INTO gtcitymast(cityname,state,country,active)values('ERODE','1','1','T');" +
                    "create table IF NOT EXISTS`gtcompmast`(`gtcompmastid` bigint NOT NULL AUTO_INCREMENT,  `gtcompmastid1` int DEFAULT NULL,  `compcode` varchar(10) DEFAULT NULL,  `compname` varchar(100) DEFAULT NULL,  `devision` varchar(50) DEFAULT NULL,  `city` bigint,  `state` bigint,  `country` bigint,  `address` varchar(500) DEFAULT NULL,  `pincode` int DEFAULT NULL,  `panno` varchar(50) DEFAULT NULL,  `tinno` varchar(50) DEFAULT NULL,  `gstno` varchar(50) DEFAULT NULL,  `gstdate` varchar(50) DEFAULT NULL,  `phoneno` varchar(50) DEFAULT NULL,  `email` varchar(50) DEFAULT NULL,  `website` varchar(50) DEFAULT NULL,  `contactname` varchar(50) DEFAULT NULL,  `active` char(1) NOT NULL DEFAULT 'T',  `ptransaction` varchar(50) DEFAULT NULL,  `partysc` varchar(50) DEFAULT NULL,  `partysno` varchar(50) DEFAULT NULL,  `createdby` varchar(100) DEFAULT NULL,  `createdon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `modifiedby` varchar(100) DEFAULT NULL,  `ipaddress` varchar(100) DEFAULT NULL,  `intime` varchar(100) DEFAULT NULL,  `outtime` varchar(100) DEFAULT NULL,  `TIME` varchar(10) DEFAULT NULL,  `lunchfrom` varchar(20) DEFAULT NULL,  `lunchto` varchar(20) DEFAULT NULL,  `breakfrom` varchar(20) DEFAULT NULL,  `breakto` varchar(20) DEFAULT NULL,  `tpr` varchar(20) DEFAULT NULL,  `eventeafrom` varchar(10) DEFAULT NULL,  `eventeato` varchar(10) DEFAULT NULL,  `PERMISSIONHRS` varchar(20) DEFAULT NULL,  PRIMARY KEY (`gtcompmastid`),foreign key (country) references gtcountrymast(gtcountrymastid),foreign key (state) references gtstatemast(gtstatemastid)) ;" +
                    "INSERT into gtcompmast(gtcompmastid1,compcode,compname,city,state,country,address,pincode,panno,tinno,gstno,gstdate,phoneno,email,website,contactname,active,ptransaction,intime,outtime,createdby,modifiedby,ipaddress)  VALUES('1','" + Class.Users.HCompcode + "','" + Class.Users.HCompcode + "', '1', '1','1' ,'S.F.NO396/2E,295/IC , MAHAVISHNU NAGER, ANGERIYAPLAYAM ROAD,TIRUPUR,641603','630610','12365410','','','','','','PS@GMAIL.IN','9751828323','T', 'COMPANY' , '9:00' ,'9:00','VAIRAM','VAIRAM','192.168.101.15');" +
                    "create table asptblschoolmas(asptblschoolmasid bigint NOT NULL AUTO_INCREMENT,`compcode` varchar(10) DEFAULT NULL,  `compname` varchar(100) DEFAULT NULL,  `devision` varchar(50) DEFAULT NULL,  `city` bigint,  `state` bigint,  `country` bigint,  `address` varchar(500) DEFAULT NULL,  `pincode` int DEFAULT NULL,  `panno` varchar(50) DEFAULT NULL,  `tinno` varchar(50) DEFAULT NULL,  `gstno` varchar(50) DEFAULT NULL,  `gstdate` varchar(50) DEFAULT NULL,  `phoneno` varchar(50) DEFAULT NULL,  `email` varchar(50) DEFAULT NULL,  `website` varchar(50) DEFAULT NULL,  `contactname` varchar(50) DEFAULT NULL,  `active` char(1) NOT NULL DEFAULT 'T',  `ptransaction` varchar(50) DEFAULT NULL,  `partysc` varchar(50) DEFAULT NULL,  `partysno` varchar(50) DEFAULT NULL,  `createdby` varchar(100) DEFAULT NULL,  `createdon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `modifiedby` varchar(100) DEFAULT NULL,  `ipaddress` varchar(100) DEFAULT NULL,  `intime` varchar(100) DEFAULT NULL,  `outtime` varchar(100) DEFAULT NULL,  `TIME` varchar(10) DEFAULT NULL,  `lunchfrom` varchar(20) DEFAULT NULL,  `lunchto` varchar(20) DEFAULT NULL,  `breakfrom` varchar(20) DEFAULT NULL,  `breakto` varchar(20) DEFAULT NULL,  `tpr` varchar(20) DEFAULT NULL,  `eventeafrom` varchar(10) DEFAULT NULL,  `eventeato` varchar(10) DEFAULT NULL,  `PERMISSIONHRS` varchar(20) DEFAULT NULL,  `EMPIMAGE` longblob,  `IMAGEBYTES` int DEFAULT NULL,  PRIMARY KEY(`asptblschoolmasid`),foreign key (country) references gtcountrymast(gtcountrymastid),foreign key (state) references gtstatemast(gtstatemastid));" +
                    "INSERT into asptblschoolmas(compcode,compname,city,state,country,address,pincode,panno,tinno,gstno,gstdate,phoneno,email,website,contactname,active,ptransaction,intime,outtime,createdby,modifiedby,ipaddress)  VALUES('CTS','CHAITANIYA TECHNO SCHOOL', '1', '1','1' ,'S.F.NO396/2E,295/IC , MAHAVISHNU NAGER, ANGERIYAPLAYAM ROAD,TIRUPUR,641603','630610','12365410','','','','','','PS@GMAIL.IN','9751828323','T', 'COMPANY' , '9:00' ,'9:00','VAIRAM','VAIRAM','192.168.101.15');" +
                    "CREATE TABLE `asptblelectionmas` (  `ASPTBLELECTIONMASID` bigint NOT NULL AUTO_INCREMENT,  `postname` varchar(50) DEFAULT NULL,  `active` char(1) NOT NULL DEFAULT 'T',  `compcode` int DEFAULT NULL,  `username` int DEFAULT NULL,  `createdby` varchar(100) DEFAULT NULL,  `createdon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `modifiedby` varchar(100) DEFAULT NULL,  `ipaddress` varchar(100) DEFAULT NULL, PRIMARY KEY(`ASPTBLELECTIONMASID`));" +
                    "create table asptblblockmas(asptblblockmasid bigint NOT NULL AUTO_INCREMENT,  `blockno` varchar(50) DEFAULT NULL,  `active` char(1) NOT NULL DEFAULT 'T',  `compcode` int DEFAULT NULL,  `username` int DEFAULT NULL,  `createdby` varchar(100) DEFAULT NULL,  `createdon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `modifiedby` varchar(100) DEFAULT NULL,  `ipaddress` varchar(100) DEFAULT NULL,  PRIMARY KEY (`asptblblockmasid`));" +
                    "create table asptblsectionmas(asptblsectionmasid bigint NOT NULL AUTO_INCREMENT,  `section` varchar(50) DEFAULT NULL,  `active` char(1) NOT NULL DEFAULT 'T',  `compcode` int DEFAULT NULL,  `username` int DEFAULT NULL,  `createdby` varchar(100) DEFAULT NULL,  `createdon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `modifiedby` varchar(100) DEFAULT NULL,  `ipaddress` varchar(100) DEFAULT NULL,  PRIMARY KEY (`asptblsectionmasid`));" +
                    "create table asptblstandardmas(asptblstandardmasid bigint NOT NULL AUTO_INCREMENT,  `standard` varchar(50) DEFAULT NULL,  `active` char(1) NOT NULL DEFAULT 'T',  `compcode` int DEFAULT NULL,  `username` int DEFAULT NULL,  `createdby` varchar(100) DEFAULT NULL,  `createdon` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,  `modifiedby` varchar(100) DEFAULT NULL,  `ipaddress` varchar(100) DEFAULT NULL,  PRIMARY KEY (`asptblstandardmasid`)) ;" +
                    "create table asptblstudentmas(asptblstudentmasid  bigint NOT NULL AUTO_INCREMENT,  `compcode` int DEFAULT NULL,  `compname` int DEFAULT NULL,  `studentname` varchar(100) DEFAULT NULL,  `lastname` varchar(100) DEFAULT NULL,  `address` varchar(500) DEFAULT NULL,  `gender` varchar(10) DEFAULT NULL,  `dateofbirth` date DEFAULT NULL,  `ROLLNO` varchar(50) DEFAULT NULL,  `dateofjoin` date DEFAULT NULL,  `standard` bigint DEFAULT NULL,  `bloodgroup` varchar(20) DEFAULT NULL,  `SECTION` bigint DEFAULT NULL,  `contact` varchar(50) DEFAULT NULL,  `BLOCKNO` bigint DEFAULT NULL, `STUDENTIMAGE` longblob,  `STUDENTVOTELOG` longblob,  `active` varchar(1) DEFAULT NULL,  `STUDENTIMAGEBYTES` int DEFAULT NULL,  `STUDENTVOTEBYTES` int DEFAULT NULL,  `username` int DEFAULT NULL,  `ipaddress` varchar(30) DEFAULT NULL,  `createdby` varchar(50) DEFAULT NULL,  `createdon` varchar(30) DEFAULT NULL,  `modifiedon` varchar(30) DEFAULT NULL,  `election` varchar(1) DEFAULT NULL,  `count` int DEFAULT NULL,  `votecount` int DEFAULT NULL,  `ELECTIONPOST` bigint DEFAULT NULL,  `ELECTIONDATE` date DEFAULT NULL,foreign key (blockno) references asptblblockmas(asptblblockmasid),foreign key (section) references asptblsectionmas(asptblsectionmasid),foreign key (standard) references asptblstandardmas(asptblstandardmasid),foreign key (ELECTIONPOST) references ASPTBLELECTIONMAS(ASPTBLELECTIONMASID),PRIMARY KEY (`asptblstudentmasid`));" +
                    "CREATE TABLE `asptblvotemas` (  `asptblvotemasid` int NOT NULL AUTO_INCREMENT,  `asptblstudentmasid` int DEFAULT NULL,  `compcode` int DEFAULT NULL,  `compname` int DEFAULT NULL,  `studentname` varchar(100) DEFAULT NULL,  `lastname` varchar(100) DEFAULT NULL,  `address` varchar(500) DEFAULT NULL,  `gender` varchar(10) DEFAULT NULL,  `dateofbirth` date DEFAULT NULL,  `ROLLNO` varchar(50) DEFAULT NULL,  `dateofjoin` date DEFAULT NULL,  `standard` bigint DEFAULT NULL,  `bloodgroup` varchar(20) DEFAULT NULL,  `SECTION` bigint DEFAULT NULL,  `contact` varchar(50) DEFAULT NULL,  `BLOCKNO` bigint DEFAULT NULL,  `election` varchar(1) DEFAULT NULL,  `votedate` datetime DEFAULT NULL,  `votecount` int DEFAULT NULL,  `active` varchar(1) DEFAULT NULL,  `username` int DEFAULT NULL,  `ipaddress` varchar(30) DEFAULT NULL,  `createdby` varchar(50) DEFAULT NULL,  `createdon` varchar(30) DEFAULT NULL,  `modifiedon` varchar(30) DEFAULT NULL,  `POSTNAME` int DEFAULT NULL,  `ELECTIONDATE` date DEFAULT NULL,  foreign key (blockno) references asptblblockmas(asptblblockmasid),  foreign key (section) references asptblsectionmas(asptblsectionmasid),  foreign key (standard) references asptblstandardmas(asptblstandardmasid),PRIMARY KEY (`asptblvotemasid`) ) ;" +
                    "create table gtdeptdesgmast(gtdeptdesgmastid bigint NOT NULL AUTO_INCREMENT,  `department` varchar(50) DEFAULT NULL,  PRIMARY KEY (`gtdeptdesgmastid`));" +
                    "create table asptblpartymas(asptblpartymasid bigint not null  auto_increment,asptblpartymasid1 integer, partycode   varchar(10),partyname varchar(100), devision varchar(50), city integer,  state integer,  country integer, address varchar(500),   pincode integer,  panno  varchar(50), tinno varchar(50),  gstno varchar(50),   gstdate varchar(50),  phoneno varchar(50), email varchar(50),   website varchar(50), contactname varchar(50),  active CHAR(1) NOT NULL DEFAULT 'T',  customer varchar(50),supplier varchar(50), partysc varchar(50),partysno varchar(50), createdby varchar(100), createdon DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, modifiedby  varchar(100),  ipaddress varchar(100), primary key(asptblpartymasid)); " +
                    "INSERT INTO asptblpartymas(asptblpartymasid1,partycode,partyname,city,state,country,active,customer,supplier)values(1,'PSA','PS PRIVATE LIMITED','1','1','1','T','CUSTORMER','');" +
                    "INSERT INTO asptblpartymas(asptblpartymasid1,partycode,partyname,city,state,country,active,customer,supplier)values(2,'SKL','SKL PRIVATE LIMITED','1','1','1','T','','CUSTORMER');" +
                    "create table pintrs_attlog(ATTLOGID bigint NOT NULL AUTO_INCREMENT,  `DATETIMERECORD` varchar(50) DEFAULT NULL,  `ENROLLNO` bigint DEFAULT NULL,  `INOUTMODE` bigint DEFAULT NULL,  `IPADDRESS` varchar(50) DEFAULT NULL,  `MACHINENUMBER` bigint DEFAULT NULL,  `VERIFYMODE` bigint DEFAULT NULL,  `WORKCODE` bigint DEFAULT NULL,  `intime` varchar(20) DEFAULT NULL,  `outtime` varchar(20) DEFAULT NULL,  `outdate` varchar(20) DEFAULT NULL,  `timediffer` varchar(20) DEFAULT NULL,  `indate` date DEFAULT NULL,  PRIMARY KEY (`ATTLOGID`)) ;" +
                    "create table pintrs_tempattlog(ATTLOGID bigint NOT NULL AUTO_INCREMENT,  `DATETIMERECORD` varchar(50) DEFAULT NULL,  `ENROLLNO` bigint DEFAULT NULL,  `INOUTMODE` bigint DEFAULT NULL,  `IPADDRESS` varchar(50) DEFAULT NULL,  `MACHINENUMBER` bigint DEFAULT NULL,  `VERIFYMODE` bigint DEFAULT NULL,  `WORKCODE` bigint DEFAULT NULL,  `indate` date DEFAULT NULL,  `intime` varchar(20) DEFAULT NULL,  `outdate` varchar(20) DEFAULT NULL,  `outtime` varchar(20) DEFAULT NULL,  `timediffer` varchar(20) DEFAULT NULL,  PRIMARY KEY (`ATTLOGID`));" +
                    "create table hrnhmast(hrnhmastid bigint(20) not null auto_increment primary key ,hrnhmastid1 bigint(20), finyear bigint(15), compcode bigint(15), compname bigint(15), docid varchar(50) ,date datetime, active varchar(1) ,compcode1 bigint(15), username int , createdby varchar(100) ,createdon varchar(50) ,modifiedby varchar(100) ,ipaddress varchar(50));" +
                    "create table asptblmacip(ASPTBLMACIPID bigint NOT NULL AUTO_INCREMENT,  `MACIP` varchar(50) DEFAULT NULL,  `ACTIVE` varchar(1) DEFAULT NULL,  `COMPCODE` int DEFAULT NULL,  `USERNAME` varchar(50) DEFAULT NULL,  `MODIFIEDON` varchar(25) DEFAULT NULL,  `CREATEDBY` varchar(50) DEFAULT NULL,  `CREATEDON` varchar(25) DEFAULT NULL,  `IPADDRESS` varchar(50) DEFAULT NULL,  `MACNO` int DEFAULT NULL,  `MTYPE` varchar(50) DEFAULT NULL,  `MTYPE2` varchar(50) DEFAULT NULL,  PRIMARY KEY (`ASPTBLMACIPID`));" +
                    "create table asptblusermas(userid bigint NOT NULL AUTO_INCREMENT,  `finyear` varchar(20) DEFAULT NULL,  `compcode` bigint DEFAULT NULL,  `empno` varchar(50) DEFAULT NULL,  `dept` bigint DEFAULT NULL,  `username` varchar(50) DEFAULT NULL,  `pasword` varchar(50) DEFAULT NULL,  `active` varchar(1) DEFAULT NULL,  `ipaddres` varchar(50) DEFAULT NULL,  `createdon` varchar(50) DEFAULT NULL,  `gatename` varchar(50) DEFAULT NULL,  `empname` bigint DEFAULT NULL,  `newpassword` varchar(100) DEFAULT NULL, sessiontime varchar(10),osuser varchar(50), PRIMARY KEY (`userid`));" +
                    "create table  asptblmenuname(menunameid    bigint not null auto_increment primary key not null,  menuname    varchar(50),  active        varchar(5),  parentmenuid  bigint(20),  createon varchar(50),  createby      varchar(50),  modifyon      varchar(50),  ipaddress    varchar(50) ); " +
                    "CREATE TABLE asptblnavigation(menuid bigint not null auto_increment primary key, menuname  varchar(100), navurl varchar(200), parentmenuid  bigint(20), active        varchar(1), menunameid    bigint(20), compcode      bigint(20), username      bigint(20), foreign key(username) references asptblusermas(userid));" +
                    "CREATE TABLE asptbluserrights(userrightsid bigint NOT NULL AUTO_INCREMENT,  `menuid` bigint NOT NULL,  `menuname` varchar(100) DEFAULT NULL,  `navurl` varchar(100) DEFAULT NULL,  `parentmenuid` int DEFAULT NULL,  `active` varchar(1) DEFAULT NULL,  `saves` varchar(1) DEFAULT NULL,  `prints` varchar(1) DEFAULT NULL,  `readonly` varchar(1) DEFAULT NULL,  `search` varchar(1) DEFAULT NULL,  `deletes` varchar(1) DEFAULT NULL,  `username` bigint NOT NULL,  `compcode` bigint NOT NULL,  `passwords` varchar(50) DEFAULT NULL,  `sno` int DEFAULT NULL,  `ipaddress` varchar(30) DEFAULT NULL,  `createdby` varchar(30) DEFAULT NULL,  `createdon` varchar(30) DEFAULT NULL,  `modifiedon` varchar(30) DEFAULT NULL,  `news` varchar(10) DEFAULT NULL,  `treebutton` varchar(50) DEFAULT NULL,  `globalsearch` varchar(50) DEFAULT NULL,  `login` varchar(50) DEFAULT NULL,  `changepassword` varchar(50) DEFAULT NULL,  `changeskin` varchar(50) DEFAULT NULL,  `download` varchar(50) DEFAULT NULL,  `contact` varchar(50) DEFAULT NULL,  `pdf` varchar(50) DEFAULT NULL,  `imports` varchar(50) DEFAULT NULL,  PRIMARY KEY (`userrightsid`),  KEY `username` (`username`),  CONSTRAINT `asptbluserrights_ibfk_1` FOREIGN KEY (`username`) REFERENCES `asptblusermas` (`userid`));" +
                    "CREATE TABLE asptblregistration(asptblregistrationid  bigint not null  AUTO_INCREMENT,finyear varchar(50), fromdate   varchar(50),   todate   varchar(50),   productid varchar(250),  licensetype  varchar(50),  noofdays     int , productkeys     varchar(250) ,days int, Active varchar(1), compcode     int , username  int , ipaddress    varchar(50), createdon  varchar(50),  createdby    varchar(50),  modifiedon varchar(50), primary key (asptblregistrationid));" +
                    "insert into asptblusermas(finyear,compcode,  empname ,  dept ,  username ,gatename,  pasword ,  active ,  ipaddres,createdon)values('1','1',1,'1','ADMIN','21-22/GJI/','kkQ25us9uHw=','T','192.168.101.15','28/01/2021 11:13:18');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('TIPL','T', 0,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('Masters','T', 1,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('Transactions','T', 1,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('TreeView','T', 1,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('Registration','T', 1,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('Reports','T', 1,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('UserMaster','T', 4,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('MenuNameMaster','T', 4,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('NavigationMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('TreeViewMaster','T', 4,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('UserRights','T', 4,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('FinYearMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('CountryMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('StateMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('CityMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('CompanyMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('EmployeeMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('DepartmentMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('IPEntry','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('NHDayEntry','T', 3,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('DeviceCommunication','T', 3,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('TimeCardProcessEntry','T',3,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('GenerateMaster','T', 5,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('RegistrationMaster','T', 5,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('AboutMaster','T', 5,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('PartyMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('DateTimeReport','T', 6,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('Report2','T', 6,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('Report3','T', 6,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('BlockMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('SectionMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('StandardMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('VotingMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('ElectionPostMaster','T', 2,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('SchoolMaster','T', 3,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('StudentMaster','T', 3,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                     "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('AutoGenerateMaster','T', 5,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                    "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('GarmentProductionEntry','T', 3,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                     "INSERT INTO asptblmenuname(MENUNAME,ACTIVE,parentmenuid,CREATEON,CREATEBY,MODIFYON,IPADDRESS) VALUES('PurchasesOrder','T', 3,'28-Jan-2021 11:26:19','','28-Jan-2021 11:26:19','192.168.101.15');" +
                     "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'TIPL' , 'TIPL' , 0 , 'T' , 1 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'Masters' , 'Masters' , 1 , 'T' , 2 , 1 , 1 );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'Transactions' , 'Transactions' , 1 , 'T' , 3 , 1 , 1  );  " +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'TreeView' , 'TreeView' , 1 , 'T' , 4 , 1 , 1  ); " +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'Registration' , 'Registration' , 1 , 'T' , 5 , 1 , 1  ); " +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'Reports' , 'Reports' , 1 , 'T' , 6 , 1 , 1  ); " +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'UserMaster' , '/TreeView/UserMaster' , 4 , 'T' , 7 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'MenuNameMaster' , '/TreeView/MenuNameMaster' , 4 , 'T' , 8 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'NavigationMaster' , '/Masters/NavigationMaster' , 4 , 'T' , 9 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'TreeViewMaster' , '/TreeView/TreeViewMaster' , 4 , 'T' , 10 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'UserRights' , '/TreeView/UserRights' , 4 , 'T' , 11 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'FinYearMaster' , '/TreeView/FinYear Master' , 4 , 'T' , 12 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'CountryMaster' , '/Masters/CountryMaster' , 2 , 'T' , 13 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'State Master' , '/Masters/State Master' , 2 , 'T' , 14 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'CityMaster' , '/Masters/City Master' , 2 , 'T' , 15 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'CompanyMaster' , '/Masters/Company Master' , 2 , 'T' , 16 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'EmployeeMaster' , '/Masters/Employee Mastery' , 2 , 'T' , 17 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'DepartmentMaster', '/Masters/Department Master' , 3 , 'T' , 18 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'IPEntry', '/Masters/IPEntry' , 2 , 'T' , 19 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'NHDayEntry' , '/Transactions/NHDay Entry' , 3 , 'T' , 20 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'DeviceCommunication' , '/Masters/DeviceCommunication' , 2 , 'T' , 21 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'TimeCardProcessEntry' , '/Transactions/TimeCardProcess Entry' , 3 , 'T' , 22 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'GenerateMaster' , '/Registration/Generate Master' , 5 , 'T' , 23 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'RegistrationMaster' , '/Registration/Registration Master' , 5 , 'T' , 24 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'AboutMaster' , '/Registration/About Master' , 5 , 'T' , 25 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'PartyMaster' , '/Masters/Party Master' , 2 , 'T' , 26 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'DateTimeReport' , '/Report/DateTimeReport' , 6 , 'T' , 27 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'Report2' , '/Reports/RReport2' , 6 , 'T' , 28 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'Report3' , '/Reports/Report3' , 6 , 'T' , 29 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'BlockMaster' , '/Masters/BlockMaster' , 2 , 'T' , 30 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'SectionMaster' , '/Masters/SectionMaster' , 2 , 'T' , 31 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'StandardMaster' , '/Masters/StandardMaster' , 2 , 'T' , 32 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'VotingMaster' , '/Masters/VotingMaster' , 2 , 'T' , 33 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'ElectionPostMaster' , '/Masters/ElectionPostMaster' , 2 , 'T' , 34 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'SchoolMaster' , '/Transactions/SchoolMaster' , 3 , 'T' , 35 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'StudentMaster' , '/Transactions/StudentMaster' , 3 , 'T' , 36 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'AutoGenerateMaster' , '/Masters/ElectionPostMaster' , 5 , 'T' , 37 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'GarmentProductionEntry' , '/Transactions/PurchasesOrder' , 3 , 'T' , 38 , 1 , 1  );" +
                    "INSERT INTO  asptblnavigation(MENUNAME,NAVURL,parentmenuid,ACTIVE,menunameid,COMPCODE,USERNAME)VALUES( 'PurchasesOrder' , '/Transactions/GarmentProductionEntry' , 3 , 'T' , 39 , 1 , 1  );" +

                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,News, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,Pdf,Imports,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) values(1,'TIPL','TIPL',0,'T','T','T','T','T','T','T',1,1,'T','T','T','T','T','T','T','T','T','28/01/2021 11:49:36','28/01/2021 11:49:36',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(2,'Masters','Masters',1,'T','T','T','T','T','T','T',1,1,'T','T','T','T','T','T','T','T','T','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(3,'Transactions','Transactions',1,'T','T','T','T','T','T','T',1,1,'T','T','T','T','T','T','T','T','T','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(4,'TreeView','TreeView',1,'T','T','T','T','T','T','T',1,1,'T','T','T','T','T','T','T','T','T','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(5,'Registration','Registration',1,'T','T','T','T','T','T','T',1,1,'T','T','T','F','F','F','F','F','F','28/01/2021 11:51:08','28/01/2021 11:51:08',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(6,'Reports','Reports',1,'T','T','T','T','T','T','T',1,1,'T','T','T','F','F','F','F','F','F','28/01/2021 11:51:08','28/01/2021 11:51:08',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,News, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,Pdf,Imports,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) values(7,'UserMaster','/TreeView/UserMaster',4,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:36','28/01/2021 11:49:36',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(8,'MenuNameMaster','/TreeView/MenuNameMaster',4,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(9,'NavigationMaster','/TreeView/NavigationMaster',4,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,News, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,Pdf,Imports,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) values(10,'TreeViewMaster','/TreeView/TreeViewMaster',4,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:36','28/01/2021 11:49:36',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(11,'UserRights','TreeView/UserRights',4,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(12,'FinYearMaster','/Masters/FinYear Master ',2,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(13,'CountryMaster','/Masters/Country Master ',2,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(14,'StateMaster','/Masters/State Master',2,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(15,'CityMaster','/Masters/City Master',2,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(16,'CompanyMaster','/Masters/Company Master',2,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(17,'EmployeeMaster','/Masters/Employee Master',2,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(18,'DepartmentMaster','/Masters/Department Master',2,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','T','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(19,'IPEntry','/Masters/IP Entry',2,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','T','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(20,'NHDayEntry','/Masters/NHDAYS Entry',3,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(21,'DeviceCommunication','/Transactions/DeviceCommunication',3,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(22,'TimeCardProcessEntry','/Transactions/TimeCardProcess Entry',3,'T','T','T','T','T','T','T',1,1,'F','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(23,'GenerateMaster','/Transactions/Generate Master',5,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(24,'RegistrationMaster','/Transactions/RegistrationMaster',5,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(25,'AboutMaster','/Registration/AboutMaster',5,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(26,'PartyMaster','/Transactions/PartyMaster',2,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(27,'DateTimeReport','/Reports/DateTimeReport',6,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(28,'Report2','/Registration/AutoGenerateMaster',5,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(29,'Report3','/Transactions/GarmentProductionEntry',3,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(30,'BlockMaster','/Transactions/PurchasesOrder',3,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');"+
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(31,'SectionMaster','/Registration/AutoGenerateMaster',5,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(32,'StandardMaster','/Transactions/GarmentProductionEntry',3,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(33,'VotingMaster','/Transactions/PurchasesOrder',3,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');"+
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(34,'ElectionPostMaster','/Registration/AutoGenerateMaster',5,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(35,'SchoolMaster','/Transactions/GarmentProductionEntry',3,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(36,'StudentMaster','/Transactions/PurchasesOrder',3,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');"+                                                                                                                                                                                                                                                                                                                            
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(37,'AutoGenerateMaster','/Registration/AutoGenerateMaster',5,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(38,'GarmentProductionEntry','/Transactions/GarmentProductionEntry',3,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');" +
                    "INSERT INTO asptbluserrights(menuid ,  MENUNAME,  NAVURL,  parentmenuid ,  ACTIVE,NEWS, SAVES, PRINTS,  READONLY ,  SEARCH ,  DELETES,COMPCODE,USERNAME,TREEBUTTON,GLOBALSEARCH,LOGIN,CHANGEPASSWORD, CHANGESKIN,DOWNLOAD,CONTACT,PDF,IMPORTS,CREATEDON,MODIFIEDON,SNO,IPADDRESS ) VALUES(39,'PurchasesOrder','/Transactions/PurchasesOrder',3,'T','T','T','T','T','T','T',1,1,'T','F','F','F','F','F','F','F','F','28/01/2021 11:49:59','28/01/2021 11:49:59',0,'192.168.101.15');";

                    progressBar1.Visible = true; lblprogress1.Visible = true; label1.Visible = true;
                    string[] words = tab.Split(';');
                    for (int i = 0; i < words.Length; i++)
                    {
                        string del = words[i].ToString() + ";";
                        Utility.ExecuteNonQuery(del);
                        label1.Text = words[i].ToString();
                        decimal per = Convert.ToDecimal(100 / Convert.ToDecimal(words.Length)) * (i);
                        lblprogress1.Refresh();
                        progressBar1.Value = (int)per;
                        lblprogress1.Text = (int)per + "%";
                        label1.Refresh();
                    }
                    Cursor = Cursors.Default;
                    MessageBox.Show("Created Successfully", "Tables", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    this.Close();

                }
                else
                {
                    this.Close();
                }
            }
            catch (Exception ex)
            {
                Cursor = Cursors.Default;

                MessageBox.Show("Butcreate_Click" + ex.ToString(), "Tables", MessageBoxButtons.OK, MessageBoxIcon.Information);
                Application.Exit();
            }
        }

  private void button1_Click(object sender, EventArgs e)
  {
string tab = "";
tab = "" +
 "DROP TRIGGER " + Class.Users.ProjectID + ".ASPTBLDEPTRI?" +
 "DROP SEQUENCE " + Class.Users.ProjectID + ".ASPTBLDEPSEQ?" +
 "DROP TABLE " + Class.Users.ProjectID + ".ASPTBLDEP CASCADE CONSTRAINTS? " +
 "DROP TRIGGER " + Class.Users.ProjectID + ".ASPTBLEMPTRI?" +
 "DROP SEQUENCE " + Class.Users.ProjectID + ".ASPTBLEMPSEQ?" +
 "DROP TABLE " + Class.Users.ProjectID + ".ASPTBLEMP CASCADE CONSTRAINTS?" +
 "DROP TRIGGER " + Class.Users.ProjectID + ".ASPTBLUSERMASTRI?" +
 "DROP SEQUENCE " + Class.Users.ProjectID + ".ASPTBLUSERMASSEQ?" +
 "DROP TABLE " + Class.Users.ProjectID + ".ASPTBLUSERMAS CASCADE CONSTRAINTS?" +
 "DROP TRIGGER " + Class.Users.ProjectID + ".ASPTBLMENUNAMETRI?" +
 "DROP SEQUENCE " + Class.Users.ProjectID + ".ASPTBLMENUNAMESEQ?" +
 "DROP TABLE " + Class.Users.ProjectID + ".ASPTBLMENUNAME CASCADE CONSTRAINTS?" +
 "DROP TRIGGER " + Class.Users.ProjectID + ".ASPTBLNAVIGATIONTRI?" +
 "DROP SEQUENCE " + Class.Users.ProjectID + ".ASPTBLNAVIGATIONseq?" +
 "DROP TABLE " + Class.Users.ProjectID + ".ASPTBLNAVIGATION CASCADE CONSTRAINTS?" +
 "DROP TRIGGER " + Class.Users.ProjectID + ".ASPTBLUSERRIGHTSTRI?" +
 "DROP SEQUENCE " + Class.Users.ProjectID + ".ASPTBLUSERRIGHTSSEQ?" +
 "DROP TABLE " + Class.Users.ProjectID + ".ASPTBLUSERRIGHTS CASCADE CONSTRAINTS?"+
 "DROP TRIGGER " + Class.Users.ProjectID + ".asptblregistrationTRI?" +
 "DROP SEQUENCE " + Class.Users.ProjectID + ".asptblregistrationSEQ?" +
 "DROP TABLE " + Class.Users.ProjectID + ".asptblregistration";
progressBar1.Visible = true; lblprogress1.Visible = true; label1.Visible = true;
string[] words = tab.Split('?');
for (int i = 0; i < words.Length; i++)
{
 string del = words[i].ToString().Trim();
 Utility.ExecuteNonQuery(del);
 label1.Text = words[i].ToString();
 decimal per = Convert.ToDecimal(100 / Convert.ToDecimal(words.Length)) * (i + 1);
 lblprogress1.Refresh();
 progressBar1.Value = (int)per;
 lblprogress1.Text = (int)per + "%";
 label1.Refresh();
}
Cursor = Cursors.Default;
MessageBox.Show("Created Successfully", "Tables", MessageBoxButtons.OK, MessageBoxIcon.Information);
  }
 }
}
